### ISSUE TITLE
MacOS porting

### ISSUE THREAD

**Issue by MilesCranmer** [jph00/latex-ppt#2]
Hi,

Love the idea. Do you have any advice on porting this to MacOS? I just see this:
<img width="411" alt="Screen Shot 2019-11-05 at 9 47 36 PM" src="https://user-images.githubusercontent.com/7593028/68264150-e7b60380-0015-11ea-84d6-dcf2f917890d.png">

Cheers,
Miles

**Comment by jph00** [comment]
No I don't, sorry
