### ISSUE TITLE
The macro cannot be found or has been disabled because of your security settings.

### ISSUE THREAD

**Issue by fnivek** [jph00/latex-ppt#3]
I keep getting the above pop up error, (The macro cannot be found or has been disabled because of your security settings.) I turned macro settings to enable all macros, and tried copying the macros.bas folder to the same location as the add in.

**Comment by mg2015started** [comment]
Absolutely the same problem, i dont know why show this error. Do we need to install latex?

**Comment by Tastaturtaste** [comment]
I've got the same problem. Keep getting the Error stated in the title.

**Comment by contagon** [comment]
I've got it too. Would love a fix when possible!

**Comment by MatthiasGabriel** [comment]
I've got the same issue when clicking on the Input LaTeX button. If I click the Enable LaTeX Button nothing seems to happen. I'm using PowerPoint for Office 365 (16.0.12624.20422) 32-bit with a Windows 10.

**Comment by amirhfarzaneh** [comment]
I have the same issue

**Comment by jph00** [comment]
Please try again now - I've reverted the PR which I believe caused this
